var productDetails = [ 
{ brandName: 'IT Cosmetics',
    productName: 'Your Skin But Better™ CC+™ Cream with SPF 50+',
    ingredients: 
     [ ' Titanium Dioxide',
       ' Zinc Oxide',
       ' Snail Secretion Filtrate',
       ' Phenyl Trimethicone',
       ' Dimethicone',
       ' Butylene Glycol',
       ' Butylene Glycol Dicaprylate/Dicaprate',
       ' Orbignya Oleifera Seed Oil',
       ' Butyloctyl Salicylate',
       ' Cetyl Peg/Ppg-10/1 Dimethicone',
       ' Cyclopentasiloxane',
       ' Cyclohexasiloxane',
       ' Magnesium Sulfate',
       ' Polyglyceryl-4 Isostearate',
       ' Dimethicone/Vinyl Dimethicone Crosspolymer',
       ' Aluminum Hydroxide',
       ' Hexyl Laurate',
       ' Stearic Acid',
       ' Calcium Stearate',
       ' Caprylyl Glycol',
       ' Triethoxycaprylylsilane',
       ' Ethylhexylglycerin',
       ' Citrus Medica Limonum (Lemon) Peel Oil',
       ' Tocopheryl Acetate',
       ' Sorbitan Isostearate',
       ' Phenoxyethanol',
       ' Citrus Aurantium Bergamia (Bergamot) Fruit Oil',
       ' 1',
       '2-Hexanediol',
       ' Disodium Edta',
       ' Citrus Aurantium Dulcis (Orange) Peel Oil',
       ' Citrus Aurantifolia (Lime) Oil',
       ' Vitis Vinifera (Grape) Seed Oil',
       ' Punica Granatum Seed Oil',
       ' Pinus Sylvestris Leaf Oil',
       ' Persea Gratissima (Avocado) Oil',
       ' Niacinamide',
       ' Citrus Grandis (Grapefruit) Peel Oil',
       ' Cholesterol',
       ' Anthemis Nobilis Flower Water',
       ' Lactobacillus/Honeysuckle Flower/Licorice Root/Morus Alba Root/Pueraria Lobata Root/Schizandra Chinensis Fruit/Scutellaria Baicalensis Root/Sophora Japonica Flower Extract Ferment Filtrate',
       ' Perfluorohexane',
       ' Olea Europaea (Olive) Leaf Extract',
       ' Glycerin',
       ' Eucalyptus Globulus Leaf Oil',
       ' Camellia Sinensis Leaf Extract',
       ' Chrysanthemum Indicum Flower Extract',
       ' Pueraria Lobata Root Extract',
       ' Perfluorodecalin',
       ' Morus Alba Fruit Extract',
       ' Magnolia Kobus Bark Extract',
       ' Glycine Soja (Soybean) Sprout Extract',
       ' Diospyros Kaki Leaf Extract',
       ' Cinnamomum Cassia Bark Extract',
       ' Artemisia Princeps Leaf Extract',
       ' Pentafluoropropane',
       ' Curcuma Longa (Turmeric) Root Extract',
       ' Steareth-20',
       ' Hydrolyzed Hyaluronic Acid',
       ' Colloidal Oatmeal',
       ' Hydrolyzed Silk',
       ' Citric Acid',
       ' Sodium Benzoate',
       ' Potassium Sorbate',
       ' Aloe Barbadensis Leaf Extract',
       ' N-Hydroxysuccinimide',
       ' Hydrolyzed Collagen',
       ' Caprylhydroxamic Acid',
       ' Tocopherol',
       ' Thiamine Hcl',
       ' Riboflavin',
       ' Retinyl Palmitate',
       ' Pantothenic Acid',
       ' Palmitoyl Oligopeptide',
       ' Niacin',
       ' Folic Acid',
       ' Chrysin',
       ' Carnitine Hcl',
       ' Biotin',
       ' Ascorbic Acid',
       ' Palmitoyl Tetrapeptide-7',
       ' Chlorhexidine Digluconate',
        'Iron Oxides,
        'Ci 77492',
       ' Ci 77491',
       ' Ci 77499)' ],
    url: 'https://www.sephora.com/product/your-skin-but-better-cc-cream-spf-50-P411885?icid2=:p411885:product' },
  { brandName: 'bareMinerals',
    productName: 'bareMinerals Original Foundation Broad Spectrum SPF 15',
    ingredients: 
     [ ' Zinc Oxide',
       ' Mica',
       ' Titanium Dioxide',
       ' Iron Oxides',
       ' Bismuth Oxychloride',
       '' ],
    url: 'https://www.sephora.com/product/bareminerals-original-foundation-broad-spectrum-spf-15-P61003?icid2=:p61003:product' },
  { brandName: 'Too Faced',
    productName: 'Born This Way Foundation',
    ingredients: 
     [ 'Water',
       ' Cyclopentasiloxane',
       ' Glycerin',
       ' Aluminum Starch Octenylsuccinate',
       ' Isododecane',
       ' Polyglyceryl-4 Isostearate',
       ' Cetyl PEG/PPG-10/1 Dimethicone',
       ' Hexyl Laurate',
       ' Dimethicone',
       ' Ethylhexyl Methoxycinnamate',
       ' Magnesium Sulfate',
       ' Diphenyl Dimethicone',
       ' Tribehenin',
       ' Triethoxycaprylylsilane',
       ' Disteardimonium Hectorite',
       ' Polysilicone-11',
       ' Propylene Carbonate',
       ' Tetrahexyldecyl Ascorbate',
       ' Cocos Nucifera Water',
       ' Ethylhexyl Palmitate',
       ' Rhododendron Ferrugineum Extract',
       ' Alcohol',
       ' Silica Dimethyl Silylate',
       ' Lecithin',
       ' Pistacia Lentiscus (Mastic) Gum',
       ' Butylene Glycol',
       ' Potassium Sorbate',
       ' Sodium Hyaluronate',
       ' EDTA',
       ' Caprylyl Glycol',
       ' Phenoxyethanol',
       ' Titanium Dioxide (CI 77891)',
       ' Iron Oxides (CI 77491',
       ' CI 77492',
       ' CI 77499' ],
    url: 'https://www.sephora.com/product/born-this-way-P397517?icid2=:p397517:product' },
  { brandName: 'Marc Jacobs Beauty',
    productName: 'Shameless Youthful-Look 24H Foundation SPF 25',
    ingredients: 
     [ 'Water',
       ' Cyclopentasiloxane',
       ' Isododecane',
       ' Cetyl PEG/PPG-10/1 Dimethicone',
       ' Caprylyl Methicone',
       ' Alcohol',
       ' Sorbitol',
       ' Polyglyceryl-4 Isostearate',
       ' Disteardimonium Hectorite',
       ' Glycerin',
       ' Nylon-12',
       ' Hexyl Laurate',
       ' Cellulose Acetate',
       ' Adipic Acid/Neopentyl Glycol Crosspolymer',
       ' Phenyl Trimethicone',
       ' Acrylates/ Polytrimethylsiloxymethacrylate Copolymer',
       ' Magnesium Sulfate',
       ' Phenoxyethanol',
       ' PEG-10 Dimethicone',
       ' Propylene Carbonate',
       ' Caprylyl Glycol',
       ' Sodium Stearoyl Glutamate',
       ' C10-18 Triglycerides',
       ' Xylitylglucoside',
       ' Silica',
       ' Aluminum Starch Octenylsuccinate',
       ' Anhydroxylitol',
       ' Triethoxycaprylylsilane',
       ' Polyisoprene',
       ' PVP',
       ' Xylitol',
       ' Tremella Fuciformis Polysaccharide',
       ' Xanthan Gum',
       ' Polyhydroxystearic Acid',
       ' Sodium Citrate',
       ' Dimethicone',
       ' Sodium Hyaluronate',
       ' Globularia Alypum Leaf Extract',
       ' Disodium EDTA',
       ' Glucose',
       ' Cetearyl Alcohol',
       ' Stearic Acid',
       ' Ceramide NP',
       ' Phytosterols',
       '  Mica',
       ' Iron Oxides',
       'Ci 77491',
       ' Ci 77492',
       ' Ci 77499)',
       ' Titanium Dioxide (Ci 77891)' ],
    url: 'https://www.sephora.com/product/shameless-youthful-look-24h-foundation-spf-25-P427500?icid2=:p427500:product' },
  { brandName: 'FENTY BEAUTY by Rihanna',
    productName: 'Pro Filt\'r Soft Matte Longwear Foundation',
    ingredients: 
     [ 'Water',
       ' Dimethicone',
       ' Talc',
       ' Peg-10 Dimethicone',
       ' Trimethylsiloxysilicate',
       ' Polypropylene',
       ' Isododecane',
       ' Cetyl Peg/Ppg-10/1 Dimethicone',
       ' Nylon-12',
       ' Hdi/Trimethylol Hexyllactone Crosspolymer',
       ' Phenoxyethanol',
       ' Sodium Chloride',
       ' Hydrogen Dimethicone',
       ' Glycerin',
       ' Magnesium Sulfate',
       ' Sodium Dehydroacetate',
       ' Disteardimonium Hectorite',
       ' Aluminum Hydroxide',
       ' Methicone',
       ' Benzoic Acid',
       ' Dehydroacetic Acid',
       ' Propylene Carbonate',
       ' Ethylhexylglycerin',
       ' Parfum/Fragrance',
       ' Silica',
       ' Biosaccharide Gum-4',
       ' Ananas Sativus (Pineapple) Fruit Extract',
       ' Carica Papaya (Papaya) Fruit Extract',
       ' Paullinia Cupana Seed Extract',
       ' Potassium Sorbate',
       ' Sorbic Acid',
       '  Titanium Dioxide (CI 77891)',
       ' Iron Oxides (CI 77491',
       ' CI 77492',
       ' CI77499).' ],
    url: 'https://www.sephora.com/product/pro-filtr-soft-matte-longwear-foundation-P87985432?icid2=:p87985432:product' },
  { brandName: 'Lancôme',
    productName: 'Teint Idole Ultra Long Wear Foundation',
    ingredients: 
     [ 'Water',
       ' Cyclopentasiloxane',
       ' Polypropysilsequioxane',
       ' Isododecane',
       ' Dimethicone',
       ' C30-45 Alkyldimethylsilyl',
       ' Polypropylsilsequioxane Silica',
       ' Glycerin',
       ' Peg-10 Dimethicone',
       ' Dimethicone/Polyglycerinej-3 Crosspolymer',
       ' Sodium Chloride',
       ' Nylon-12',
       ' Paraffin',
       ' Cyclomethione',
       ' Aluminum Hydroxide',
       ' Disodium Edta',
       ' Disodium Stearoyl Glutamate',
       ' Dipropylene Glycol',
       ' Disteardimonium Hectorite',
       ' Acrylates Copolymer',
       ' Phenoxyethanol Chlorphenesin',
       ' Ethylparaben',
       'CI 77007',
       'Ultramarines',
       ' CI 77491',
       ' CI 77492',
       ' CI 77499',
       'Iron Oxides',
       ' CI 77891',
       'Titanium Dioxide' ],
    url: 'https://www.sephora.com/product/teint-idole-ultra-24h-long-wear-foundation-P308201?icid2=:p308201:product'
  },
  { brandName: 'La Mer',
    productName: 'The Moisturizing Soft Cream',
    ingredients: 
     [ 'Algae (Seaweed) Extract',
       ' Cyclopentasiloxane',
       ' Petrolatum',
       ' Glyceryl Distearate',
       ' Phenyl Trimethicone',
       ' Butylene Glycol',
       ' Hydrogenated Vegetable Oil',
       ' Cholesterol',
       ' Butyrospermum Parkii (Shea Butter)',
       ' Steareth-10',
       ' Dimethicone',
       ' Glyceryl Stearate Se',
       ' Polysilicone-11',
       ' Sesamum Indicum (Sesame) Seed Oil',
       ' Medicago Sativa (Alfalfa) Seed Powder',
       ' Helianthus Annuus (Sunflower) Seedcake',
       ' Prunus Amygdalus Dulcis (Sweet Almond) Seed Meal',
       ' Eucalyptus Globulus (Eucalyptus) Leaf Oil',
       ' Sodium Gluconate',
       ' Copper Gluconate',
       ' Calcium Gluconate',
       ' Magnesium Gluconate',
       ' Zinc Gluconate',
       ' Tocopheryl Succinate',
       ' Niacin',
       ' Sesamum Indicum (Sesame) Seed Powder',
       ' Water',
       ' Citrus Aurantifolia (Lime) Peel Extract',
       ' Laminaria Digitata Extract',
       ' Crithmum Maritimum Extract',
       ' Salicornia Herbacea Extract',
       ' Plankton Extract',
       ' Chlorella Vulgaris Extract',
       ' Glycine Soja (Soybean) Seed Extract',
       ' Glycerin',
       ' Caffeine',
       ' Sea Salt',
       ' Micrococcus Lysate',
       ' Diethylhexyl Succinate',
       ' Adenosine Phosphate',
       ' Creatine',
       ' Hydrolyzed Algin',
       ' Isocetyl Stearoyl Stearate',
       ' Cetyl Alcohol',
       ' Sucrose',
       ' Acetyl Hexapeptide-8',
       ' Glucose Oxidase',
       ' Polyacrylamide',
       ' Acetyl Carnitine Hcl',
       ' Glucose',
       ' Caprylic/Capric Triglyceride',
       ' C13-14 Isoparaffin',
       ' Tocopheryl Acetate',
       ' Tetrahexyldecyl Ascorbate',
       ' Sodium Pca',
       ' Glycosaminoglycans',
       ' Urea',
       ' Distearyldimonium Chloride',
       ' Dipalmitoyl Hydroxyproline',
       ' Sodium Hyaluronate',
       ' Laureth-7',
       ' Lecithin',
       ' Trehalose',
       ' Polyquaternium-51',
       ' Lactoperoxidase',
       ' Hydroxypropyl Cyclodextrin',
       ' Cyanocobalamin',
       ' Pentylene Glycol',
       ' Fragrance (Parfum)',
       ' Disodium Edta',
       ' Bht',
       ' Citronellol',
       ' Hydroxycitronellal',
       ' Geraniol',
       ' Linalool',
       ' Limonene',
       ' Potassium Sorbate',
       ' Phenoxyethanol'],
    url: 'https://www.sephora.com/product/the-moisturizing-soft-cream-P416342?icid2=:p416342:product' },
  { brandName: 'FARSÁLI',
    productName: 'Unicorn Essence',
    ingredients: 
     [ ' Water',
       ' Propanediol',
       ' Glycerin',
       ' Polysorbate 20',
       ' Glyceryl Polyacrylate',
       ' Euterpe Oleracea (Açaí) Fruit Extract',
       ' Vaccinium Angustifolium (Blueberry) Fruit Extract',
       ' Lycium Barbarum (Goji) Fruit Extract',
       ' Sambucus Nigra (Elder Berry) Fruit Extract',
       ' Tamarindus Indica Seed Polysaccharide',
       ' Phenoxyethanol',
       ' Ethylhexylglycerin',
       ' Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer',
       ' Vanilla Planifolia Fruit Extract',
       ' Citrus Aurantium Bergamia (Bergamot) Fruit Oil',
       ' Citrus Paradisi (Grapefruit) Peel Oil',
       ' Red 33',
       ' Red 4',
       ' Blue 1',
       ' Mica',
       ' Titanium Dioxide' ],
    url: 'https://www.sephora.com/product/unicorn-essence-P417141?icid2=:p417141:product' },
  { brandName: 'Drunk Elephant',
    productName: 'Lala Retro™ Whipped Cream',
    ingredients: 
     [ 'Water',
       ' Glycerin',
       ' Caprylic Capric Triglyceride',
       ' Isopropyl Isostearate',
       ' Pseudozyma Epicola/Camellia Sinensis Seed Oil/Glucose/Glycine Soja Meal/Malt Extract/Yeast Extract Ferment Filtrate (Pseudozyma Epicola/Camellia Sinensis Seed Oil/Glucose/Yeast Extract Ferment Filtrate)',
       ' Stearic Acid',
       ' Glyceryl Stearate SE',
       ' Cetearyl Alcohol',
       ' Pentylene Glycol',
       ' Plantago Lanceolata Leaf Extract',
       ' Adansonia Digitata Seed Oil',
       ' Citrullus Lanatus (Watermelon) Seed Oil',
       ' Passiflora Edulis Seed Oil',
       ' Schinziophyton Rautanenii Kernel Oil',
       ' Sclerocarya Birrea Seed Oil',
       ' Polyglyceryl-6 Ximenia Americana Seedate',
       ' Sodium Hyaluronate Crosspolymer',
       ' Ceteareth-20',
       ' Trisodium Ethylenediamine Disuccinate',
       ' Sodium Hydroxide',
       ' Citric Acid',
       ' Carbomer',
       ' Xanthan Gum',
       ' Caprylyl Glycol',
       ' Chlorphenesin',
       ' Phenoxyethanol',
       ' Ethylhexylglycerin' ],
    url: 'https://www.sephora.com/product/lala-retro-whipped-cream-P408645?icid2=:p408645:product' },
  { brandName: 'Kiehl\'s Since 1851',
    productName: 'Ultra Facial Cream',
    ingredients: 
     [ 'Water',
       'Glycerin',
       'Cyclohexasiloxane',
       'Squalane',
       'Bis-Peg-18 Methyl Ether Dimethyl Silane',
       'Sucrose Stearate',
       'Stearyl Alcohol',
       'Peg-8 Stearate',
       'Urea',
       'Myristyl Myristate',
       'Pentaerythrityl Tetraethylhexanoate',
       'Prunus Armeniaca Kernel Oil',
       'Phenoxyethanol',
       'Persea Gratissima Oil',
       'Olea Europaea Oil',
       'Oryza Sativa Bran Oil',
       'Cetyl Alcohol',
       'Glyceryl Stearate',
       'Imperata Cylindrica Root Extract',
       'Stearic Acid',
       'Methylparaben',
       'Chlorphenesin',
       'Palmitic Acid',
       'Disodium Edta',
       'Acrylates/C10-30 Alkyl Acrylate Crosspolymer',
       'Propylparaben',
       'Carbomer',
       'Triethanolamine',
       'Prunus Amygdalus Dulcis Oil',
       'Xanthan Gum',
       'Sodium Hydroxide',
       'Tocopherol',
       'Pseudoalteromonas Ferment Extract',
       'Hydroxypalmitoyl Sphinganine',
       'Caprylyl Glycol.' ],
    url: 'https://www.sephora.com/product/ultra-facial-cream-P421996?icid2=:p421996:product' },
  { brandName: 'Drunk Elephant',
    productName: 'Protini™ Polypeptide Cream',
    ingredients: 
     [ 'Water',
       ' Dicaprylyl Carbonate',
       ' Glycerin',
       ' Cetearyl Alcohol',
       ' Cetearyl Olivate',
       ' Sorbitan Olivate',
       ' Sclerocarya Birrea Seed Oil',
       ' Bacillus/Soybean/ Folic Acid Ferment Extract',
       ' Nymphaea Alba Root Extract',
       ' sh-Oligopeptide-1',
       ' sh-Oligopeptide-2',
       '  sh-Polypeptide-1',
       ' sh-Polypeptide-9',
       ' sh-Polypeptide-11',
       ' Copper Palmitoyl Heptapeptide-14 ',
       ' Heptapeptide-15 Palmitate',
       ' Palmitoyl Tetrapeptide-7',
       ' Palmitoyl Tripeptide-1',
       ' Alanine',
       ' Arginine',
       ' Glycine',
       ' Histidine ',
       ' Isoleucine',
       ' Phenylalanine',
       ' Proline',
       ' Serine',
       ' Threonine',
       ' Valine',
       ' Acetyl Glutamine',
       ' Coconut Alkanes ',
       ' Coco-Caprylate/Caprate',
       ' Sodium Hyaluronate',
       ' Aspartic Acid',
       ' Linoleic Acid',
       ' Linolenic Acid',
       ' Lecithin',
       ' Butylene Glycol ',
       ' Polyvinyl Alcohol',
       ' Sodium Lactate',
       ' Sodium PCA',
       ' PCA',
       ' Sorbitan Isostearate',
       ' Carbomer ',
       ' Polysorbate 20 ',
       ' Polysorbate 60',
       ' Lactic Acid/Glycolic Acid Copolymer',
       ' Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate Copolymer',
       ' Xanthan Gum',
       ' Isomalt',
       '2-Hexanediol',
       ' Caprylyl Glycol',
       ' Chlorphenesin',
       ' Phenoxyethanol',
       ' Tocopherol',
       ' Sodium Benzoate',
       ' Phenylpropanol',
       ' Glyceryl Caprylate',
       ' Symphytum Officinale Callus Culture Extract' ],
    url: 'https://www.sephora.com/product/protini-tm-polypeptide-cream-P427421?icid2=:p427421:product' },
  { brandName: 'belif',
    productName: 'The True Cream Aqua Bomb',
    ingredients: 
     [ ' Water',
       ' Dipropylene Glycol',
       ' Glycerin',
       ' Methl Trimethicone',
       ' Alcohol Denat',
       ' Dimethicone',
       ' Cyclopentasiloxane',
       '2-Hexanediol',
       ' Malakite Extract',
       ' Caprylic/Capric Triglyceride',
       ' Pentaerythrityl Tetraethylhexanoate',
       ' PEG/PPG/Polybutylene Glycol-8/5/3 Glycerin',
       ' Alchemilla Vulgaris Leaf Extract*',
       ' Equisetum Arvense Leaf Extract*',
       ' Stellaria Media (Chickweed) Extract*',
       ' Urtica Dioica (Nettle) Leaf Extract*',
       ' Plantago Lanceolata Leaf Extract*',
       ' Avena Sativa (Oat) Kernel Extract**',
       ' Calendula Officinalis Flower Extract**',
       ' Nepeta Cataria Extract**',
       ' Rubus Idaeus (Raspberry) Leaf Extract**',
       ' Baptisia Tinctoria Root Extract**',
       ' Dimethiconol',
       ' Polymethylsilsesquioxane',
       ' Sodium Acrylate/Acryloyldimethyltaurate/Dimethylacrylamide Crosspolymer',
       ' Isohexadecane',
       ' Polysorbate 60',
       ' Ceramide 3',
       ' Cholesterol',
       ' Butyrospermum Parkii (Shea) Butter',
       ' Phenl Trimethicone',
       ' Pentaerythrityl Tetraisostearate',
       ' Panthenol',
       ' Squalane',
       ' Triethylhexanoin',
       ' Macadamia Ternifolia Seed Oil',
       ' PEG-150',
       ' PEG-40 Hydrogenated Castor Oil',
       ' Acrylates/C10-30 Alkyl Acrylate Crosspolymer',
       ' C14-22 Alcohols',
       ' Arachidyl Glucoside',
       ' Hydrogenated Lecithin',
       ' PEG-100 Stearate',
       ' Stearic Acid',
       ' Glyceryl Stearate',
       ' Carbomer',
       ' Tromethamine',
       ' Trisodium EDTA',
       ' Fragrance+',
       ' Citronellol',
       ' Limonene',
       ' Citral',
       ' Geraniol',
       ' Linalool' ],
    url: 'https://www.sephora.com/product/the-true-cream-aqua-bomb-P394639?icid2=:p394639:product' },
  { brandName: 'Fresh',
    productName: 'Lotus Youth Preserve Face Cream with Super 7 Complex ',
    ingredients: 
     [ ' Water',
       ' Glycerin',
       ' Propylene Glycol Dicaprylate/Dicaprate',
       ' Pentylene Glycol',
       ' Cetearyl Alcohol',
       ' Caprylic/Capric Triglyceride',
       ' Cetearyl Isononanoate',
       ' Betaine',
       ' Polymethyl Methacrylate',
       ' Steareth-21',
       ' Phenoxyethanol',
       ' Behenyl Alcohol',
       ' Cetearyl Glucoside',
       ' Sorbitol',
       ' Dimethicone',
       ' Sodium Pca',
       ' Tocopheryl Acetate',
       ' Caprylyl Glycol',
       ' Carbomer',
       ' Tromethamine',
       ' Cetyl Alcohol',
       ' Stearyl Alcohol',
       ' Butylene Glycol',
       ' Xanthan Gum',
       ' Sodium Hyaluronate',
       ' Limonene',
       ' Ficus Carica (Fig) Fruit Extract',
       ' Lepidium Meyenii Root Extract',
       ' Citrus Limon (Lemon) Peel Oil',
       ' Cucumis Sativus (Cucumber) Fruit Extract',
       ' Ascorbyl Tetraisopalmitate',
       ' Caramel',
       ' Algae Extract',
       ' Citric Acid',
       ' Nelumbo Nucifera Flower Extract',
       ' Citral',
       ' Potassium Sorbate',
       ' Hibiscus Esculentus Fruit Extract',
       ' Sorbic Acid',
       ' Tocopherol' ],
    url: 'https://www.sephora.com/product/lotus-youth-preserve-face-cream-with-super-7-complex-P377123?icid2=:p377123:product' },
  { brandName: 'Glow Recipe',
    productName: 'Watermelon Pink Juice Moisturizer',
    ingredients: 
     [ ' Watermelon Extract',
       ' Hyaluronic Acid',
       ' Citrullus Lanatus (Watermelon) Fruit',
       '  Hydrolyzed Wheat Protein',
       ' Hydrolyzed Soy Protein',
       ' Hydrolyzed Corn Protein',
       ' Glutamic Acid (Derived from Fermented Grains)',
       ' Glycerin',
       ' Cetearyl Olivate (Derived from Olive)',
       ' Sorbitan Olivate (Derived from Olive)',
      ' Sodium Hyaluronate',
       ' Cetyl Alcohol',
       ' Cyamopsis Tetragonoloba (Guar) Gum',
       ' Xanthan Gum',
       ' Apricot Kernel Amino Acid',
       ' Alkanna Tinctoria Root Extract',
       ' Scutellaria Baicalensis Root Extract',
       ' Paeonia Suffruticosa (Peony) Root Extract',
       ' Glycyrrhiza Glabra (Licorice) Root Extract',
       ' Beta-Glucan',
       ' Jasminum Grandiflorum (Jasmine) Flower Wax',
       ' Acrylates/C10-30 Alkyl Acrylate Crosspolymer',
       ' Brassica Oleracea Capitata (Cabbage) Leaf Extract',
       ' Ipomoea Batatas (Sweet Potato) Root Extract',
       ' Fragrance' ],
    url: 'https://www.sephora.com/product/watermelon-pink-juice-moisturizer-P428819?icid2=:p428819:product' },
  { brandName: 'Dr. Jart+',
    productName: 'Ceramidin™ Cream',
    ingredients: 
     [ ' Water',
       ' Glycerin',
       ' Dipropylene Glycol',
       ' Caprylic/Capric Triglyceride',
       ' Hydrogenated Poly(C6-14 Olefin)',
       ' Hydrogenated Polydecene',
       ' Cetearyl Alcohol',
       ' 2-Hexanediol',
       ' Dimethicone',
       ' Cyclomethicone',
       ' Vegetable Oil',
       ' Bifida Ferment Lysate',
       ' Glyceryl Stearate SE',
       ' Dimethiconol',
       ' Cyclopentasiloxane',
       ' Ulmus Davidiana Root Extract',
       ' Amaranthus Caudatus Seed Extract',
       ' Piper Methysticum Leaf/Root/Stem Extract',
       ' Beta Vulgaris (Beet) Root Extract',
       ' Algae Extract',
       ' Artemisia Vulgaris Extract',
       ' Portulaca Oleracea Extract',
       ' Pueraria Thunbergiana Root Extract',
       ' Glycyrrhiza Glabra (Licorice) Root Extract',
       ' Paeonia Lactiflora Root Extract',
       ' Cnidium Officinale Root Extract',
       ' Hydrogenated Lecithin',
       ' Sodium Hyaluronate',
       ' Citrus Aurantium Bergamia (Bergamot) Fruit Oil',
       ' Soluble Collagen',
       ' Pelargonium Graveolens Flower Oil',
       ' Aloe Barbadensis Leaf Juice',
       ' Salvia Officinalis (Sage) Oil',
       ' Pogostemon Cablin Oil',
       ' Cetearyl Glucoside',
       ' Cetearyl Olivate',
       ' Sorbitan Olivate',
       ' C12-16 Alcohols',
       ' Ceramide 3',
       ' Microcrystalline Cellulose',
       ' Hydroxyethyl Acrylate/Sodium Acryloyldimethyl Taurate',
       ' Copolymer',
       ' Squalane',
       ' Glyceryl Stearate',
       ' Peg-100 Stearate',
       ' Hydrolyzed Corn Starch',
       ' Palmitic Acid',
       ' Coco-Caprylate/Caprate',
       ' Polysorbate 60',
       ' Caramel',
       ' Cellulose Gum',
       ' Propylene Glycol',
       ' Butylene Glycol',
       ' Disodium EDTA',
       ' Panthenol',
       ' Acacia Senegal Gum',
       ' Folic Acid',
       ' Acetic Acid',
       ' Cholesterol',
       ' Raffinose',
       ' Lactic Acid',
       ' Xanthan Gum',
       ' Tromethamine',
       ' Palmitoyl Pentapeptide-4' ],
    url: 'https://www.sephora.com/product/ceramidin-cream-P382354?icid2=:p382354:product' },
  { brandName: 'FARSÁLI',
    productName: 'Rose Gold Elixir',
    ingredients: 
     [ 'Rosa Rubiginosa (Rosehip) Seed Oil',
       ' Carthamus Tinctorius (Safflower) Seed Oil',
       ' Cucurbita Pepo (Pumpkin) Seed Oil',
       ' Gold',
       ' Cymbopogon Flexuosus (Lemongrass) Oil',
       ' Citrus Aurantium Dulcis (Orange) Peel Oil',
       ' Tocopheryl Acetate (Vitamin E)' ],
    url: 'https://www.sephora.com/product/rose-gold-elixir-P417139?icid2=:p417139:product' },
  { brandName: 'Tatcha',
    productName: 'The Water Cream',
    ingredients: 
     [ ' Saccharomyces/Camellia Sinensis Leaf/Cladosiphon Okamuranus/Rice Ferment Filtrate*',
       ' Dimethicone',
       ' Propanediol',
       ' Glycerin',
       ' Diglycerin',
       ' Diphenylsiloxy Phenyl Trimethicone',
       ' Gold',
       ' Belamcanda Chinensis Root Extract',
       ' Rosa Multiflora Fruit Extract',
       ' Houttuynia Cordata Extract',
       ' Sophora Angustifolia Root Extract',
       ' Sodium Hyaluronate',
       ' Lecithin',
       ' Pistacia Lentiscus (Mastic) Gum',
       ' Sodium Chloride',
       ' Sodium Citrate',
       ' Mica',
       ' Peg-9 Polydimethylsiloxyethyl Dimethicone',
       ' Dimethicone/Peg-10/15 Crosspolymer',
       ' Dimethicone/Phenyl Vinyl Dimethicone Crosspolymer',
       ' Disodium Edta',
       ' Tin Oxide',
       ' Titanium Dioxide',
       ' Butylene Glycol',
       ' Ethylhexylglycerin',
       ' Parfum/Fragrance',
       ' Alcohol',
       ' Phenoxyethanol' ],
    url: 'https://www.sephora.com/product/the-water-cream-P418218?icid2=:p418218:product' }
]

 module.exports = productDetails;
